# Generated by Django 4.2.3 on 2024-01-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsmodel',
            name='product_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
