# Generated by Django 4.2.3 on 2024-01-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category_description', models.CharField(blank=True, max_length=125)),
                ('category_image', models.ImageField(blank=True, upload_to='images/categories')),
            ],
        ),
    ]
